# Generated by Django 4.1.3 on 2022-11-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('priority', models.IntegerField()),
                ('status', models.IntegerField()),
                ('created', models.DateField()),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
